mongo-service:
 image: mongodb
 ports:
  - "27017:27017"
 volumes:
  - mongodatabase:/data/db

node-service:
 image: node-compose
 ports: 
  - "3000:3000"
 volumes:
  - /usr/src/application:/usr/src/app/source

