mongocontainer:
 image: mongodb
 container_name: mongocontainer
 ports:
  - "27017:27017"
 volumes:
  - mongodatabase:/data/db

nodeservice:
 build: .
 container_name: nodeservice
 links:
  - mongocontainer
 ports: 
  - "3000:3000"
 volumes:
  - ./:/usr/src/app/source
  - /usr/src/app/source/node_modules

